name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 960
        check_interval: 60
        environment: ${{ fromJSON('["", "production"]')[github.ref == 'refs/heads/main'] }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test 
      env:
        CI: true
        BASE_URL: ${{ github.event.deployment_status.target_url }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30